# .streamlit/config.toml

[theme]
base="light"
primaryColor="#008080"  # teal accent, you can change it
backgroundColor="#FAFAFA"  # soft broken white
secondaryBackgroundColor="#F0F0F5"  # subtle gray for cards/sidebars
textColor="#222222"  # dark gray, easy to read
font="sans serif"
